const ActionTypes = {
  FETCH_EPISODES_ERROR: 'FETCH_EPISODES_ERROR',
  FETCH_EPISODES_REQUEST: 'FETCH_EPISODES_REQUEST',
  FETCH_EPISODES_SUCCESS: 'FETCH_EPISODES_SUCCESS',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  RESET_TITLE: 'RESET_TITLE',
  SEARCH_TV_SHOW: 'SEARCH_TV_SHOW',
  SEARCH_TV_SHOW_ERROR: 'SEARCH_TV_SHOW_ERROR',
  SEARCH_TV_SHOW_REQUEST: 'SEARCH_TV_SHOW_REQUEST',
  SEARCH_TV_SHOW_SUCCESS: 'SEARCH_TV_SHOW_SUCCESS',
};

export { ActionTypes as default, ActionTypes };
